# resource "local_file" "pet" {
# filename = var.filename
# content = "My favorite pet is ${random_pet.my-pet.id}" # Implicit dependency
# }
resource "local_file" "pet" {
  filename = var.filename
  content  = var.content["statement1"]
  
  lifecycle {
    create_before_destroy = true
    prevent_destroy = true
    ignore_changes = [ 
      filename, content
     ]
  }
}
resource "random_pet" "my-pet" {
  prefix    = var.prefix[1]
  separator = var.separator
  length    = var.length
}
output "pet-name" {
  value       = random_pet.my-pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}